name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget \
          autoconf automake libtool gettext libltdl-dev

        pip install --upgrade pip
        pip install buildozer cython

    - name: Download and configure Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip -d cmdline-tools
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        mv cmdline-tools/* $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest

        # Create symlink to satisfy old Buildozer path expectations
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest $HOME/.buildozer/android/platform/android-sdk/tools

        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"

    - name: Initialize buildozer.spec if not present
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug
