name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget \
          autoconf automake libtool pkg-config libffi-dev libssl-dev \
          libltdl-dev libncurses-dev zlib1g zlib1g-dev \
          ccache libpng-dev libjpeg-dev

        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize Buildozer (preserve your spec)
      run: |
        buildozer init || true

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: jangre-random-machine-apk
        path: bin/*.apk
